name: API Proxy for data.json

on:
  repository_dispatch:
    types: [get-data, update-data]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Handle GET request
        if: github.event.action == 'get-data'
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/tiagodeazevedoferreira/CalculoHorarioSaida/contents/data.json
      - name: Handle PUT request
        if: github.event.action == 'update-data'
        env:
          DATA: ${{ github.event.client_payload.data }}
        run: |
          SHA=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                     -H "Accept: application/vnd.github.v3+json" \
                     https://api.github.com/repos/tiagodeazevedoferreira/CalculoHorarioSaida/contents/data.json | jq -r .sha)
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -H "Content-Type: application/json" \
               -d "{\"message\":\"Atualizar data.json\",\"content\":\"$DATA\",\"sha\":\"$SHA\"}" \
               https://api.github.com/repos/tiagodeazevedoferreira/CalculoHorarioSaida/contents/data.json
